<?php
namespace modava\video\components;

use backend\components\MyController;

class MyVideoController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
